spring.application.name=storageservice
spring.config.import= optional:configserver:http://localhost:8888


#server.port=8086
#cloud.aws.credentials.access-key=
#cloud.aws.credentials.secret-key=
#cloud.aws.region.static=
#aws.bucket.name=appshala-drive-storage
#
## Eureka Server config
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#eureka.instance.prefer-ip-address=true
#eureka.instance.hostname=localhost
